version: "3.9"

services:
  db:
    image: mariadb:11
    container_name: logwatchai-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: logwatchai
      MYSQL_USER: loguser
      MYSQL_PASSWORD: logpass
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: [ "CMD-SHELL", "mariadb -h localhost -uloguser -plogpass -e 'Select 1'" ]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 30s

  app:
    build:
      context: .
    container_name: logwatchai-app
    restart: always
    environment:
      # Database
      SPRING_DATASOURCE_URL: jdbc:mariadb://db:3306/logwatchai
      SPRING_DATASOURCE_USERNAME: loguser
      SPRING_DATASOURCE_PASSWORD: logpass
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      # JWT-Config
      JWT_SECRET: "a87f8d9c6bb04a65d4af77fd8c9b15eaa73729c3fae243bda85ef31c59d19f72"
      # mail-config
      SPRING_MAIL_HOST: mailhog
      SPRING_MAIL_PORT: 1025
      SPRING_MAIL_USERNAME: ""
      SPRING_MAIL_PASSWORD: ""
      SPRING_MAIL_PROPERTIES_MAIL_SMTP_AUTH: "false"
      SPRING_MAIL_PROPERTIES_MAIL_SMTP_STARTTLS_ENABLE: "false"
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./shared-logs:/shared-logs

  log-generator:
    build:
      context: ../loggenerator
    container_name: loggenerator-app
    restart: always
    ports:
      - "9090:8080"
    environment:
      LOG_OUTPUT: /logs/test.log
    volumes:
      - ./shared-logs:/shared-logs     # Shared logs
    depends_on:
      db:
        condition: service_healthy

  mailhog:
    image: mailhog/mailhog
    container_name: logwatchai-mailhog
    restart: always
    ports:
      - "1025:1025"   # SMTP
      - "8025:8025"   # Web UI

volumes:
  db_data:
  logs:
