watchPaths:
  - "../shared-logs/test.log"

alerting:
  rules:
    - name: High severity events
      severityAtLeast: HIGH

    - name: Critical anomaly score
      anomalyScoreMin: 0.8

    - name: Database related issues
      textContains: ["database", "sql", "connection failed"]


reportEmail: "admin@example.com"

ai:
  models:
    - name: "openai"
      enabled: true
      model: "gpt-4o-mini"
      key: "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"

    - name: "perplexity"
      enabled: false
      model: "mixtral-small"
      key: "not available yet"

    - name: "anthropic"
      enabled: false
      model: "anotherone-small"
      key: "not available yet"

    - name: "local"
      enabled: false
      model: "any"
      key: "not available yet"


security:
  users:
    - username: "admin"
      password: "secret123"
      roles: ["ADMIN"]