spring:
  application:
    name: logwatchai

  main:
    allow-circular-references: true

  datasource:
    hikari:
      initialization-fail-timeout: 60000
      connection-timeout: 30000
    url: jdbc:mariadb://db:3306/logwatchai
    username: loguser
    password: logpass
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MariaDBDialect
    hibernate:
      ddl-auto: update # Schema automatisch anpassen (f√ºr Dev/PoC)
    show-sql: false  # less sql-queries
    properties:
      hibernate:
        format_sql: false # no formating for no output
        jdbc:
          lob:
            non_contextual_creation: true

  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true

  mail:
    host: smtp.example.com
    port: 587
    username: your-email@example.com
    password: your-email-password
    properties:
      mail:
        smtp:
          auth: true
          starttls.enable: true

server:
  port: 8080

logging:
  level:
    root: WARN
    org.springframework: WARN
    org.hibernate: WARN
    org.hibernate.SQL: OFF
    org.hibernate.type: OFF

    # ========== DEBUGING ==========
    #com.bbu.solution: DEBUG
    #org.springframework.web.client.RestTemplate: DEBUG
    #io.jsonwebtoken: DEBUG
    #org.hibernate.SQL: DEBUG
    #org.hibernate.type.descriptor.sql: TRACE
    #com.theokanning.openai: DEBUG
    #com.bbu.solution.application.alert: DEBUG       # AlertEmailListener, EmailService
    #com.bbu.solution.application.decision: DEBUG    # DecisionEngineServiceImpl
    #com.bbu.solution.infrastructure.email: DEBUG    # EmailService intern
    #=============================================================
jwt:
  secret: ${JWT_SECRET}
  expiration-ms: 3600000 # 1 Stunde

app:
  config-file: /app/config/logwatchai.yaml

  # place for more configurations